export const gameCategories = [
  {label: "Acción"},
  {label: "Aventura"},
  {label: "Carreras"},
  {label: "Casual"},
  {label: "Deportes"},
  {label: "Estrategia"},
  {label: "Exploración"},
  {label: "FPS"},
  {label: "Indie"},
  {label: "MOBA"},
  {label: "Mundo Abierto"},
  {label: "Narrativa"},
  {label: "Novela Visual"},
  {label: "Plataformas"},
  {label: "Puzzle"},
  {label: "Realidad Virtual"},
  {label: "Retro"},
  {label: "RPG"},
  {label: "Simulación"},
  {label: "Sigilo"},
  {label: "Supervivencia"},
  {label: "Sandbox"},
  {label: "Terror"},
];
